POST http://localhost:8080/auth/register
Content-Type:  application/json

{
    "UserName": "testuser",
    "Email": "testuser@example.com",
    "Password": "password123",
    "ProfilePicture": "http://example.com/profile.jpg",
    "IsVerified": false,
    "emailToken": "random-token"
}


POST http://localhost:8080/auth/login
Content-Type: application/json

{
    "Email": "testuser@example.com",
    "Password": "password123",
}