# 1. Get All Users
GET http://localhost:8080/api/users
Content-Type: application/json

###

# 2. Get User by ID
GET http://localhost:8080/api/users/1
Content-Type: application/json

###

# 3. Update User by ID
PUT http://localhost:8080/api/users/user10@example.com
Content-Type: application/json

{
  "username": "updateduser",
  "email": "user10@example.com",
  "country": "Canada",
  "interests": "reading, traveling",
  "is_verified": true
}

###

# 4. Delete User by ID
DELETE http://localhost:8080/api/users/1
Content-Type: application/json
