### Get all countries
GET http://localhost:8080/api/countries/
Accept: application/json

### Create a new country
POST http://localhost:8080/api/countries/
Content-Type: application/json

{
  "Name": "United States",
  "Capital": "Washington, D.C.",
  "Continent": "North America",
  "Currency": "USD",
  "LivingExpense": 1800.0,
  "LifeStyleRating": 7.1,
  "Population": 331000000,
  "Language": "English",
  "AverageTemperature": 13.0,
  "UniqueField": "Diverse Opportunities",
  "Description": "Known for its cultural diversity and economic opportunities.",
  "SafetyIndex": 52.7,
  "HealthcareIndex": 69.1,
  "CostOfLivingIndex": 70.1,
  "PollutionIndex": 56.0,
  "ClimateType": "Varied",
  "EconomicFreedomRank": 15
}
### Update an existing country
PUT http://localhost:8080/api/countries/1
Content-Type: application/json

{
  "Name": "United States",
  "Capital": "Washington, D.C.",
  "Continent": "North America",
  "Currency": "USD",
  "LivingExpense": 1800.0,
  "LifeStyleRating": 7.1,
  "Population": 331000000,
  "Language": "English",
  "AverageTemperature": 13.0,
  "UniqueField": "Diverse Opportunities",
  "Description": "Known for its cultural diversity and economic opportunities.",
  "SafetyIndex": 52.7,
  "HealthcareIndex": 69.1,
  "CostOfLivingIndex": 70.1,
  "PollutionIndex": 56.0,
  "ClimateType": "Varied",
  "EconomicFreedomRank": 15
}

### Delete an existing country
POST http://localhost:8080/api/recomendation/
Content-Type: application/json

{
  "expectedLivingCost": 2000.00,
  "expectedLifeStyleRate": 8.0,
  "expectedAverageTemperature": 20.0,
  "reasonToMove": "Job opportunity"
}
